config = {
    'model': dict(type='resnet50',
                  params=dict(dropout=True,
                              dropout_prob=0.2)),
    'train': dict(num_epochs=100,
                  batch_size=64,
                  optimizer=dict(type='SGD',
                                 param=dict(lr=0.0008,
                                            # betas=(0.9, 0.999),
                                            # eps=1e-8
                                            momentum=0.9
                                            )),
                  scheduler=dict(step_size=10,
                                 gamma=0.2),
                  lambda_u=80,
                  dataset=dict(K=2,
                               alpha=0.75,
                               labeled_transform=dict(crop=True,
                                        input_size=64,
                                        h_flip=True,
                                        h_flip_p=0.3,
                                        v_flip=True,
                                        v_flip_p=0.3,
                                        gaussian_blur=False,
                                        kernel_size=11,
                                        sigma=5,
                                        gaussian_blur_p=0.1),
                               unlabeled_transform=dict(crop=True,
                                        input_size=64,
                                        h_flip=True,
                                        h_flip_p=0.3,
                                        v_flip=True,
                                        v_flip_p=0.3,
                                        gaussian_blur=False,
                                        kernel_size=11,
                                        sigma=5,
                                        gaussian_blur_p=0.1)),
                  ),
    'finetune': dict(finetuning=True,
                     num_epochs=100,
                     batch_size=64,
                     optimizer=dict(type='Adam',
                                    param=dict(lr=0.001,
                                               betas=(0.9, 0.999),
                                               eps=1e-8)),
                     scheduler=dict(step_size=10,
                                    gamma=0.1),
                     dataset=dict(transform=dict(crop=True,
                                        input_size=64,
                                        h_flip=True,
                                        h_flip_p=0.3,
                                        v_flip=True,
                                        v_flip_p=0.3,
                                        gaussian_blur=False,
                                        kernel_size=11,
                                        sigma=5,
                                        gaussian_blur_p=0.1)),
                     criterion='ce'),
    'val': dict(input_size=64,
                batch_size=64,
                transform=dict(crop=False,
                               input_size=64,
                               h_flip=False,
                               h_flip_p=0.5,
                               v_flip=False,
                               v_flip_p=0.5,
                               gaussian_blur=False,
                               kernel_size=11,
                               sigma=5,
                               gaussian_blur_p=0.5)),
    'data_dir': '/home/stu6/EuroSAT_PRML24/Task_B',
    'work_dir': '/home/stu6/2024PRML_Project2/TaskB'
}