config = {
    'model': dict(type='resnet18',
                  load_from=None,
                  binary_class=False,
                  threshold=0.5,
                  params=dict(
                      dropout=True,
                      dropout_prob=0.1
                  )),
    'train': dict(num_epochs=60,
                  batch_size=64,
                  optimizer=dict(type='SGD',
                                 param=dict(
                                     lr=0.0008,
                                     # betas=(0.9, 0.999),
                                     # eps=1e-8,
                                     momentum=0.9
                                 )),
                  scheduler=dict(step_size=10,
                                 gamma=0.1),
                  dataset=dict(transform=dict(crop=True,
                                   input_size=64,
                                   h_flip=True,
                                   h_flip_p=0.5,
                                   v_flip=True,
                                   v_flip_p=0.5,
                                   gaussian_blur=False,
                                   kernel_size=11,
                                   sigma=5,
                                   gaussian_blur_p=0.1))),
    'val': dict(batch_size=64,
                transform=dict(crop=False,
                               input_size=64,
                               h_flip=False,
                               h_flip_p=0.5,
                               v_flip=False,
                               v_flip_p=0.5,
                               gaussian_blur=False,
                               kernel_size=11,
                               sigma=5,
                               gaussian_blur_p=0.5)),
    ####################################################
    #'assign_label': dict(batch_size=64,
    #                     T=5.0,
    #                     K=2,
    #                     transform=dict(crop=True,
    #                                    input_size=64,
    #                                    h_flip=True,
    #                                    h_flip_p=0.3,
    #                                    v_flip=True,
    #                                    v_flip_p=0.3,
    #                                    gaussian_blur=False,
    #                                    kernel_size=11,
    #                                    sigma=5,
    #                                    gaussian_blur_p=0.1)),
    'data_dir': '/home/stu6/EuroSAT_PRML24/Task_A',
    'work_dir': '/home/stu6/2024PRML_Project2/TaskA'
}